management:
  security.enabled: false
  server.port: 9405
  prometheus:
    enabled: true
  endpoints:
    web:
      exposure.include: prometheus
  metrics:
    distribution:
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99

server:
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  jpa:
    properties:
      hibernate:
        generate_statistics: false
